title: "Fedot"
date: 2020-05-28
theme: jekyll-theme-minimal
description: > # this means to ignore newlines until "baseurl:"
  <div class='menu-group'>
    <div class='main-menu-item'><a href="/FEDOT.Docs/autolearning/main">Automated learning</a></div>
    <div class='menu-item'><a href="/FEDOT.Docs/autolearning/automl">Modern AutoML solutions</a></div>
    <div class='menu-item'><a href="/FEDOT.Docs/autolearning/composite">Composite models</a></div>
    <div class='menu-item'><a href="/FEDOT.Docs/autolearning/knowledge-enrichment">Knowledge enrichment</a></div>
   </div>
  <div class='menu-group'>
    <div class='main-menu-item'><a href="/FEDOT.Docs/fedot/main">Fedot Framework</a></div>
    <div class='menu-item'><a href="/FEDOT.Docs/fedot/quick-start">Quick start</a></div>
    <div class='menu-item'><a href="/FEDOT.Docs/fedot/components">Main components</a></div>
    <div class='menu-item'><a href="/FEDOT.Docs/fedot/algorithm-chains">Key algorithms</a></div>
    <div class='menu-item'><a href="/FEDOT.Docs/fedot/models">Models</a></div>
    <div class='menu-item'><a href="/FEDOT.Docs/fedot/tutorials">Tutorials</a></div>
  </div>
  <div class='menu-group'>
    <div class='main-menu-item'><a href="/FEDOT.Docs/real_cases/main">Real-world cases</a></div>
    <div class='menu-item'><a href="/FEDOT.Docs/real_cases/credit-scoring">Credit scoring</a></div>
    <div class='menu-item'><a href="/FEDOT.Docs/real_cases/metocean-forecasting">Metocean Forecasting</a></div>
  </div>
   <div class='menu-group'>
    <div class='main-menu-item'><a href="/FEDOT.Docs/utilities/main">Utilities</a></div>
    <div class='menu-item'><a href="/FEDOT.Docs/utilities/synthetic-generator">Synthetic datasets</a></div>
   </div>
  <div class='menu-group'>
    <div class='main-menu-item'><a href="/FEDOT.Docs/contribution/main">Contribution</a></div>
    <div class='menu-item'><a href="/FEDOT.Docs/contribution/how-to-fedot-based">How to use and adopt</a></div>
    <div class='menu-item'><a href="/FEDOT.Docs/contribution/how-to-embed">How to extend</a></div>
    <div class='menu-item'><a href="/FEDOT.Docs/contribution/guidelines">Repository guidelines</a></div>
    <div class='menu-item'><a href="/FEDOT.Docs/contribution/citation">How to cite</a></div>
  </div>
  <div class='menu-group'>
      <div class='main-menu-item'><a href="/FEDOT.Docs/FAQ">FAQ</a></div>
   </div>
  <div class='menu-group'>
     <div class='main-menu-item'><a href="/FEDOT.Docs/about-us">About us</a></div>
  </div>

    
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage


